# Generated by Django 4.1.5 on 2023-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_catalog_alter_details_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='departure',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='return_date',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
