# Generated by Django 4.1.5 on 2023-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_idnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idnum',
            name='idno',
            field=models.CharField(max_length=10),
        ),
    ]
